### ISSUE TITLE
Getting urn:acme:error:unauthorized

### ISSUE THREAD

**Issue by chattes** [Valian/docker-nginx-auto-ssl#16] opened 2019-01-17 08:04 UTC
Hi,
I am novice with Docker as Well as nginx.
I used your image to auto generate SSL Certs but getting the following error

```
nginx_1    | + Generating account key...
nginx_1    | + Registering account key with ACME server...
nginx_1    | Processing cheappr.io
nginx_1    |  + Signing domains...
nginx_1    |  + Creating new directory /etc/resty-auto-ssl/letsencrypt/certs/cheappr.io ...
nginx_1    |  + Generating private key...
nginx_1    |  + Generating signing request...
nginx_1    |  + Requesting challenge for cheappr.io...
nginx_1    |  + Responding to challenge for cheappr.io...
nginx_1    | Invalid challenge: DOMAIN=cheappr.io RESPONSE={
nginx_1    |   "type": "http-01",
nginx_1    |   "status": "invalid",
nginx_1    |   "error": {
nginx_1    |     "type": "urn:acme:error:unauthorized",
nginx_1    |     "detail": "Invalid response from http://cheappr.io/.well-known/acme-challenge/ovvIn18cLW8VCTLH1yL0ZZH72wBl576klHM4DI0LweE: \"\u003c!DOCTYPE HTML PUBLIC \\\"-//IETF//DTD HTML 2.0//EN\\\"\u003e\\n\u003chtml\u003e\u003chead\u003e\\n\u003ctitle\u003e404 Not Found\u003c/title\u003e\\n\u003c/head\u003e\u003cbody\u003e\\n\u003ch1\u003eNot Found\u003c/h1\u003e\\n\u003cp\"",
nginx_1    |     "status": 403
nginx_1    |   },
nginx_1    |   "uri": "https://acme-staging.api.letsencrypt.org/acme/challenge/YTBjeRSdSsmRCcs2WFWWK7FlscgtlVp-mu0dRujAZXQ/223605224",
nginx_1    |   "token": "ovvIn18cLW8VCTLH1yL0ZZH72wBl576klHM4DI0LweE",
nginx_1    |   "validationRecord": [
nginx_1    |     {
nginx_1    |       "url": "http://cheappr.io/.well-known/acme-challenge/ovvIn18cLW8VCTLH1yL0ZZH72wBl576klHM4DI0LweE",
nginx_1    |       "hostname": "cheappr.io",
nginx_1    |       "port": "80",
nginx_1    |       "addressesResolved": [
nginx_1    |         "174.138.120.19",
nginx_1    |         "2400:6180:100:d0::292:2001"
nginx_1    |       ],
nginx_1    |       "addressUsed": "2400:6180:100:d0::292:2001"
nginx_1    |     }
nginx_1    |   ]
nginx_1    | }
nginx_1    |  err: # !! WARNING !! Extra configuration directory /etc/resty-auto-ssl/letsencrypt/conf.d exists, but no configuration found in it.
nginx_1    | , context: ssl_certificate_by_lua*, client: 49.207.56.253, server: 0.0.0.0:443
nginx_1    | 2019/01/17 07:59:19 [error] 23#23: *4 [lua] ssl_certificate.lua:92: issue_cert(): auto-ssl: issuing new certificate failed: dehydrated failure, context: ssl_certificate_by_lua*, client: 49.207.56.253, server: 0.0.0.0:443
```

My Docker-Compose.yml
```
version: "2.2"
services:
  nginx:
    image: valian/docker-nginx-auto-ssl
    restart: on-failure
    volumes:
      - ssl_data:/etc/resty-auto-ssl
      - ./nginx:/etc/nginx/conf.d
      - ./www:/etc/nginx/data/www
    ports:
      - 80:80
      - 443:443
    depends_on:
      - app
    environment:
      ALLOWED_DOMAINS: "cheappr.io"
      LETSENCRYPT_URL: "https://acme-staging.api.letsencrypt.org/directory"
```

And my nginx file
```
       upstream app {
         server app:3000;
     }

    server {
    listen 443 ssl http2;
    server_name cheappr.io;
    # remember about this line!
    include resty-server-https.conf;

    location / {
        root /etc/nginx/data/www;
        try_files $uri /index.html;
        expires -1;

    }
    location /api {
        try_files $uri $uri/ @backend;
    }


    location @backend {
            proxy_pass http://app;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
    }
    }
```
Do you see any issues with Configuration?
Any help would be much appreciated.
Thanks

**Comment by Laboltus** [comment] 2019-04-04 19:03
You should replace include resty-server-https.conf with include resty-server-http.conf

**Comment by Valian** [comment] 2019-04-18 22:03
If you want to replace whole `nginx.conf` file, please follow instructions in [README.md](https://github.com/Valian/docker-nginx-auto-ssl#your-own-nginxconf). My guess is you forgot to include section responsible for handling HTTP traffic:

```
  include resty-http.conf;

  server {
    listen 80 default_server;
    include resty-server-http.conf;
  }
```

but I'm not sure since your nginx.conf snippet you've posted here seems to be incomplete. @Laboltus  `resty-server-https.conf` is required in https server section. 

On the other hand, if you don't need something really custom from this image, try to just stick to ENV variables, they should be able to handle 90% most common use cases ;) Closing for now, as this problem seems to be caused by invalid configuration.

**Closed by Valian** 2019-04-18 22:03 UTC
